### PR TITLE
fix: Receive() can receive dropped messages

### LINKED ISSUE #2: Receive() can receive dropped messages
I don't think that DropMessage is defined correctly. In particular, it does not actually remove messages from the variables `messages`. Instead, it decrements the counter for the given message, if it already exists in `messages`. This has two issues:
- `messages` is not a function from Message to Nat, as the comment above message suggests. Instead, it is a function from Message to Int.
- Receive only requires that the received message be in the domain of `messages`, which means that it can continue to receive messages that have been dropped (even if their count drops below zero).

### PR DESCRIPTION
**Pull request by liang636600**
Hi @ongardie, I'd be happy to submit a PR for Issue #2 . 
close #2

### CODE REVIEW

**Comment by liang636600** [comment]
https://github.com/ongardie/raft.tla/blob/fb894bded7a1b02179d77a3db1f4d1072a5b1a1b/raft.tla#L116-L117

**Comment by ongardie** [comment]
Thanks @liang636600! This fix looks reasonable to me, but as I mentioned in #2, I haven't touched TLA+ for many years.

@dricketts or @wego1236 (or anyone else more familiar with TLA+), would you mind reviewing this small fix?

**Comment by liang636600** [comment]
Hello, @ongardie, @dricketts, @wego1236, I also conducted a simple test. The test involves performing a Send(m) action followed by a Discard(m) action. I wrote a basic TLA+ code and used TLC to generate state graphs. Figure 1 shows the state graph generated using the original WithoutMessage action, while Figure 2 shows the state graph generated after I modified the WithoutMessage action.
before
Figure 1. The state graph generated using the original WithoutMessage action.
after
Figure 2. The state graph generated after modifying WithoutMessage.

As you can see, in the original state graph, when a message's counter reaches zero, the message still remains in the messages variable. However, after modifying the WithoutMessage action, the state graph shows that the messages variable is empty, which leads me to believe the modification is correct. I hope this can also assist with your review.

**Comment by ongardie** [comment]
Ok, I'm going ahead and merging this now.

**Pull request merged**
